#!/usr/bin/env bash
#
# original script from: https://github.com/ThePrimeagen/.dotfiles

if [[ $# -eq 1 ]]; then
	selected=$1
else
	dirstring=$(cat $HOME/.local/scripts/.tmux-directories)
	_dirs=($dirstring)
	existing=()
	for i in ${_dirs[@]}; do
		path=${i/#\~/$HOME}
		if [ -d $path ]; then
			existing+=($path)
		fi
	done
	# https://thevaluable.dev/practical-guide-fzf-example/
	if command -v fd &>/dev/null; then
		selected=$(fd . ${existing[@]} -p -H -L -d 1 -t d | fzf --layout reverse --multi --margin=30%,20%,30%,20% --info=inline --prompt="󰼇 " --pointer="󰳟" --border=rounded)
	else
		selected=$(find -L ${existing[@]} -mindepth 1 -maxdepth 1 -type d | fzf --layout reverse --multi --margin=30%,20%,30%,20% --info=inline --prompt="󰼇 " --pointer="󰳟" --border=rounded)
	fi
fi

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

get_conda_command() {

	# get conda env name and command
	conda_command=""
	if [ -d "$selected/.venv" ]; then
		conda_command="tmux-windowizer $selected_name conda activate $selected/.venv"
	elif [ "$selected_name" != "" ]; then
		selected_env="$(conda env list | grep -F "$selected_name" | awk '{print $2}' | xargs)"
		if [ ! -z "$selected_env" ]; then
			conda_command="tmux-windowizer $selected_name conda activate $selected_env"
		fi
	fi
	# conda_command="$conda" # trim whitespace
}

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
	get_conda_command
	if [[ -z $conda_command ]] || [[ "$conda_command" == "" ]]; then
		tmux new-session -s $selected_name -c $selected
	else
		tmux new-session -s $selected_name -c $selected "$conda_command"
	fi
	exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
	get_conda_command
	# create new session and run conda command if exists
	if [[ -z $conda_command ]] || [[ "$conda_command" == "" ]]; then
		tmux new-session -ds $selected_name -c $selected
	else
		tmux new-session -ds $selected_name -c $selected "$conda_command"
	fi
fi

if [[ -z $TMUX ]]; then
	tmux attach -t $selected_name
else
	tmux switch-client -t $selected_name
fi
