#!/usr/bin/env fish

branch_name=$(basename $1)
session_name=$(tmux display-message -p "#S")
clean_name=$(echo $branch_name | tr "./" "__")
target="$session_name:$clean_name"

if not tmux has-session -t=$selected_name 2>/dev/null
	tmux neww -dn $clean_name
end

shift
tmux send-keys -t $target "$*" Enter
