#!/usr/bin/env fish

set selected (cat ~/.local/scripts/.tmux-cht-languages ~/.local/scripts/.tmux-cht-command | fzf)
if not string length -q -- $selected 
    echo "Nothing selected, exiting."
    exit 0
end
echo "Selected: $selected";
read -p "Enter Query: " query

if grep -qs "$selected" ~/.tmux-cht-languages
    query=`echo $query | tr ' ' '+'`
    tmux neww bash -c "echo \"curl cht.sh/$selected/$query/\" & curl cht.sh/$selected/$query & while [ : ]; do sleep 1; done"
else
    tmux neww bash -c "curl -s cht.sh/$selected~$query | less"
end
