#!/usr/bin/env fish

# original script from: https://github.com/ThePrimeagen/.dotfiles

argparse -X 1 n/name -- $argv

if test (count $argv) -eq 1
    set selected $argv[1]
else
    set dirs (cat $HOME/.local/scripts/.tmux-directories)
    set existing ()
    for i in $dirs
        set path (string replace "~" "$HOME" $i)
        if test -e $path
            set existing $existing $path
        end
    end
    # 	# https://thevaluable.dev/practical-guide-fzf-example/
    if command -q fd
        set selected $(fd . $existing -p -H -L -d 1 -t d | fzf --layout reverse --multi --margin=30%,20%,30%,20% --info=inline --prompt="󰼇 " --pointer="󰳟" --border=rounded)
    else
        set selected $(find -L $existing -mindepth 1 -maxdepth 1 -type d | fzf --layout reverse --multi --margin=30%,20%,30%,20% --info=inline --prompt="󰼇 " --pointer="󰳟" --border=rounded)
    end
end

if not string length -q -- $selected
    exit 0
end

#
set selected_name $(basename "$selected" | tr . _)
set tmux_running $(pgrep tmux)
set conda_command ""

if set -q TMUX
    echo hello $TMUX
end

if not set -q TMUX #[[ -z $TMUX ]]; then
    # echo attach $TMUX $selected_name
    tmux attach -t "$selected_name"
else
    echo switch $TMUX $selected_name
    # 	tmux switch-client -t "$selected_name"
end
