vim.g.mapleader = " "
vim.g.maplocalleader = ","
vim.g.loaded_ruby_provider = 0
vim.g.loaded_perl_provider = 0
vim.g.python3_host_prog = require("utils").get_provider_python()
vim.g.ipy_celldef = "^#\\s*%%"
vim.g.autoformat = true -- format on save; toggle with <leader>uf (buffer: vim.b.autoformat)

local o = vim.o
o.number = true
o.relativenumber = true
o.signcolumn = "yes:1"
o.cursorline = true
o.wrap = false
o.linebreak = true
o.breakindent = true
o.foldcolumn = "0"
o.foldmethod = "expr"
o.foldexpr = "v:lua.vim.treesitter.foldexpr()"
o.foldlevel = 99 -- open everything on load
o.foldlevelstart = 99
o.foldtext = "" -- keep syntax highlighting on folded lines
o.laststatus = 3 -- one global statusline
o.showtabline = 0
o.showmode = false -- lualine shows it
o.termguicolors = true
o.title = true
o.pumheight = 10
o.winborder = "rounded" -- every float: hover, signature, diagnostics, pickers
o.updatetime = 250
o.timeoutlen = 400
o.hidden = false
o.autowriteall = true
o.undofile = true
o.clipboard = "unnamedplus"
o.mouse = "a"
o.splitbelow = true
o.splitright = true
o.virtualedit = "block"
o.expandtab = true
o.shiftwidth = 2
o.tabstop = 2
o.smartindent = true
o.ignorecase = true
o.smartcase = true
o.spell = false
o.completeopt = "menu,menuone,noinsert"
o.conceallevel = 1
o.fillchars = "eob: "
o.shortmess = o.shortmess .. "sI"
