# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# format = """\
# $os\
# $username\
# $directory\
# $all\
# $line_break\
# $character"""

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

# format = """$os\
# $all\
# $git_branch\
# $git_commit\
# $git_state\
# $git_metrics\
# $git_status\
# $character"""

# everything else to the right
command_timeout = 2500


[shell]
fish_indicator = '󰈺 '
powershell_indicator = '_'
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = true

[time]
disabled = true
format = ' [[$time]($style)]($style) '

[character]
# success_symbol="[󰕏](green)"
# success_symbol = "[ ](blue)"
# success_symbol = "[ ](blue)"
# error_symbol = "[ ](bold red)"
# success_symbol = "[ ](blue)"
# error_symbol = "[ ](bold red)"
# success_symbol = "[](blue)"
# error_symbol = "[](red)"
# success_symbol = "[󰘳](bold blue)"
# error_symbol = "[󰘳](bold red)"
success_symbol = "[;](bold bright-black)"
# success_symbol = "[](blue)"
# error_symbol = "[;](bold red)"
# success_symbol = "[](green)"
error_symbol = "[](bold red)"
vimcmd_symbol = "[ ](bold yellow)"

[line_break]
disabled = false

[fill]
symbol = " "
style = ''

[conda]
symbol = " "
format = '\([$symbol$environment]($style)\) '
ignore_base = true

[python]
# symbol = " "
# format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
# # symbol = "\ue73c "
format = "[$virtualenv]($style) "
style = "bright-black"
detect_extensions = []
detect_files = []

[package]
symbol = "󰏗 "
format = '[$symbol$version]($style) '

[lua]
symbol = " "
format = '[$symbol($version )]($style)'

[rust]
symbol = " "
format = '[$symbol($version )]($style)'
# symbol = "\ue7a8 "

[directory]
read_only = " 󰌾"
format = "\uf07b [$path]($style)[$read_only]($read_only_style) "

[username]
# format = "\uf007 [$user]($style) "
format = "[$user]($style) "
disabled = false
show_always = false

[hostname]
ssh_symbol = " "
format = '[$ssh_symbol$hostname]($style) '
style = 'bold dimmed green'
ssh_only = true

[swift]
format = '[$symbol($version )]($style)'
symbol = " "

[git_branch]
symbol = " "
# format = "[$symbol$branch(:$remote_branch)]($style) "
format = "[$branch]($style) "
style = "bright-black"

[cmd_duration]
format = " [$duration]($style) "
style = "yellow"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
conflicted = "≠"
modified = "!${count}"
untracked = "?${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
stashed = "↤${count}"
staged = "+${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
renamed = "≫${count}"
deleted = "✘${count}"

[os]
disabled = true

########### Nerd-Font Symbols

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[bun]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "            #" "# 
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[scala]
symbol = " "

[zig]
symbol = " "
