# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """\
$os\
$username\
$directory\
$all\
$line_break\
$character"""

# everything else to the right
# right_format = """\
# $all
# """
command_timeout = 2500


[shell]
fish_indicator = '󰈺 '
powershell_indicator = '_'
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = true

[time]
disabled = true
format = ' [[$time]($style)]($style) '

[character]
# success_symbol = "[](green)"
# error_symbol = "[](bold red)"
vimcmd_symbol = "[](bold yellow)"

[line_break]
disabled = false

[fill]
symbol = " "
style = ''

[conda]
symbol = " "
format = '\([$symbol$environment]($style)\) '
ignore_base = true

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
# symbol = "\ue73c "

[package]
symbol = "󰏗 "
format = '[$symbol$version]($style) '

[lua]
symbol = " "
format = '[$symbol($version )]($style)'

[rust]
symbol = " "
format = '[$symbol($version )]($style)'
# symbol = "\ue7a8 "

[directory]
read_only = " 󰌾"
format = "\uf07b [$path]($style)[$read_only]($read_only_style) "

[username]
# format = "\uf007 [$user]($style) "
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_symbol = " "
format = '[$ssh_symbol$hostname]($style) '
style = 'bold dimmed green'
ssh_only = true

[swift]
format = '[$symbol($version )]($style)'
symbol = " "

[git_branch]
symbol = " "
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
conflicted = "≠"
modified = "!${count}"
untracked = "?${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
stashed = "↤${count}"
staged = "+${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
renamed = "≫${count}"
deleted = "✘${count}"

[os]
disabled = false

########### Nerd-Font Symbols

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "            #" "# 
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[scala]
symbol = " "

[zig]
symbol = " "
